// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrb33aVaPny6Jv5_37xunTPZCF10TY8Pk',
    appId: '1:453023301593:web:133cad70368f4ee36ee3c8',
    messagingSenderId: '453023301593',
    projectId: 'balochify-17',
    authDomain: 'balochify-17.firebaseapp.com',
    storageBucket: 'balochify-17.firebasestorage.app',
    measurementId: 'G-QRC2L2SMGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNRzQfxOulzhq5Ts1LyU2okxhfnruYXk',
    appId: '1:453023301593:android:6bc98111399c56c36ee3c8',
    messagingSenderId: '453023301593',
    projectId: 'balochify-17',
    storageBucket: 'balochify-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE01SCyBry1G3CbyvOYakrTkPhqo_TIcM',
    appId: '1:453023301593:ios:485a32cbdc1e35ea6ee3c8',
    messagingSenderId: '453023301593',
    projectId: 'balochify-17',
    storageBucket: 'balochify-17.firebasestorage.app',
    iosBundleId: 'com.example.balochify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE01SCyBry1G3CbyvOYakrTkPhqo_TIcM',
    appId: '1:453023301593:ios:485a32cbdc1e35ea6ee3c8',
    messagingSenderId: '453023301593',
    projectId: 'balochify-17',
    storageBucket: 'balochify-17.firebasestorage.app',
    iosBundleId: 'com.example.balochify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrb33aVaPny6Jv5_37xunTPZCF10TY8Pk',
    appId: '1:453023301593:web:7a4c286dfeab8df86ee3c8',
    messagingSenderId: '453023301593',
    projectId: 'balochify-17',
    authDomain: 'balochify-17.firebaseapp.com',
    storageBucket: 'balochify-17.firebasestorage.app',
    measurementId: 'G-B45V8DLCK6',
  );
}
